[package]
name = "wslforge"
version = "1.16.0"
edition = "2021"
authors = ["mirai-toto"]
description = "WSL instance manager using YAML configuration"
license = "MIT"
repository = "https://github.com/mirai-toto/wslforge"

[package.metadata.release]
sign-commit = false
sign-tag = false
push = false
publish = false
tag = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
serde = { version = "1", features = ["derive"] }
url = { version = "2", features = ["serde"] }
serde_yaml = "0.9"
log = "0.4"
encoding_rs = "0.8"
shellexpand = "3"
expand_str = "0.1"
minijinja = "1"
sha-crypt = { version = "0.5", features = ["rand"] }
dialoguer = "0.12.0"
indicatif = "0.18.4"
comfy-table = "7.2.2"
console = "0.16.3"
fern = "0.7.1"
chrono = { version = "0.4.44", features = ["clock"] }
ureq = "2"
tempfile = "3"
tar = "0.4"
