instances:
  UbuntuFiles:
    override: true
    username: wsluser
    image:
      type: distro
      name: Ubuntu

    files:
      # Copy a single file into the instance
      - src: "configs/motd.txt"
        dest: /etc/motd
        mode: "644"

      # Copy the entire configs directory into the instance
      - src: "configs"
        dest: /home/wsluser/configs
        owner: wsluser
        mode: "755"
