instances:
  WslforgeWaitTest:
    override: true
    username: wsluser
    password: root
    install_dir: "%userprofile%/VMs"
    cloud_init:
      type: inline
      content: |
        #cloud-config
        manage_etc_hosts: true

        users:
          - name: {{ username }}
            groups: sudo
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            lock_passwd: false
            passwd: "{{ password_hash | default('') }}"

        write_files:
          - path: /etc/wsl.conf
            permissions: '0644'
            content: |
              [boot]
              systemd=true
              [user]
              default={{ username }}

        runcmd:
          - sleep 120

        final_message: "✅ cloud-init wait test finished."
    image:
      type: distro
      name: Ubuntu
